//! Three jobs: Tauri's codegen, the `Info.plist` macOS reads before it will
//! hand this process Bluetooth, and the GATT name tables the injected shim
//! needs to answer `BluetoothUUID.getService()` synchronously.

use std::fmt::Write as _;
use std::path::Path;

/// Link `Info.plist` into the Mach-O image.
///
/// macOS gates Bluetooth behind TCC and reads
/// `NSBluetoothAlwaysUsageDescription` from the running image. A bundle
/// supplies it from `Contents/Info.plist`; a bare `cargo run` binary has no
/// bundle, so the plist goes into a `__TEXT,__info_plist` section instead.
/// Without it the process is reported `Unauthorized` and is never prompted —
/// every site would see `getAvailability()` answer `false` with nothing to
/// explain why.
///
/// The path has to be absolute: a relative one is resolved against the
/// directory cargo was invoked from, not against this file.
///
/// It lives in `macos/` rather than at the crate root, and that is not
/// tidiness. The Tauri CLI merges a crate-root `Info.plist` into the
/// *generated iOS* plist, so keeping it there put `NSPrincipalClass =
/// NSApplication`, `LSMinimumSystemVersion = 10.15` and a
/// `CFBundleExecutable` naming the wrong binary into the iOS bundle — which
/// then would not install at all, because the name did not match the
/// executable Xcode had produced. `Info.ios.plist` is the iOS half.
fn embed_info_plist(os: &str) {
    if os != "macos" {
        return;
    }
    let dir = std::env::var("CARGO_MANIFEST_DIR").expect("cargo sets this");
    println!("cargo::rerun-if-changed=macos/Info.plist");
    println!("cargo::rustc-link-arg=-Wl,-sectcreate,__TEXT,__info_plist,{dir}/macos/Info.plist");
}

/// `name 0000xxxx-0000-1000-8000-00805f9b34fb`, one per line, `#` comments.
///
/// The same files `webbluetooth-core` vendors and resolves names from, read
/// here rather than duplicated: `BluetoothUUID.getService('heart_rate')` is a
/// *synchronous* call in the specification, so the shim cannot ask Rust and
/// needs the table in JavaScript. Reading the one source keeps the two answers
/// from drifting.
fn table(spec: &Path, name: &str) -> String {
    println!("cargo::rerun-if-changed={}", spec.display());
    let source =
        std::fs::read_to_string(spec).unwrap_or_else(|e| panic!("reading {}: {e}", spec.display()));

    let mut out = format!("  {name}: {{\n");
    for line in source.lines() {
        let line = line.split('#').next().unwrap_or("").trim();
        if line.is_empty() {
            continue;
        }
        // A line that does not parse is skipped rather than failing the build,
        // matching how the Rust side reads the same file: an unknown name is
        // an error at the call site, which is what it would be anyway.
        let Some((key, uuid)) = line.split_once(char::is_whitespace) else {
            continue;
        };
        let uuid = uuid.trim().to_ascii_lowercase();
        if uuid.len() != 36 {
            continue;
        }
        let _ = writeln!(out, "    {:?}: {:?},", key, uuid);
    }
    out.push_str("  },\n");
    out
}

fn generate_uuid_tables() {
    let spec = Path::new("../../crates/webbluetooth-core/spec");
    let mut js = String::from(
        "// Generated by build.rs from crates/webbluetooth-core/spec/. Do not edit.\n\
         const ASSIGNED = {\n",
    );
    js.push_str(&table(&spec.join("gatt-assigned-services.txt"), "service"));
    js.push_str(&table(
        &spec.join("gatt-assigned-characteristics.txt"),
        "characteristic",
    ));
    js.push_str(&table(
        &spec.join("gatt-assigned-descriptors.txt"),
        "descriptor",
    ));
    js.push_str("};\n");

    let out = std::path::PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("assigned.js");
    std::fs::write(out, js).expect("writing assigned.js");
}

fn main() {
    // `tauri_build::build()` emits these; declaring them keeps the compiler
    // from warning about a cfg it cannot see the definition of.
    println!("cargo::rustc-check-cfg=cfg(desktop)");
    println!("cargo::rustc-check-cfg=cfg(mobile)");

    generate_uuid_tables();
    embed_info_plist(&std::env::var("CARGO_CFG_TARGET_OS").unwrap_or_default());
    tauri_build::build();
}
