#!/usr/bin/env python3
"""Record MDN's status for each Web Bluetooth member.

The IDL says what the standard *defines*; it carries no notion of a member
being deprecated or experimental, and no notion of whether anything ships it.
MDN's browser-compat-data carries exactly that, and nothing else does — which
is why both are vendored rather than one replacing the other.

The conformance test uses this to check claims it would otherwise be taking on
faith: an exclusion that says "deprecated" has to be corroborated here.
"""

import json
import pathlib
import sys
import urllib.request

INDEX = "https://api.github.com/repos/mdn/browser-compat-data/contents/api"
BASE = "https://raw.githubusercontent.com/mdn/browser-compat-data/main/api"


def fetch(url: str):
    with urllib.request.urlopen(url, timeout=60) as response:
        return json.load(response)


def main() -> None:
    files = sorted(
        f["name"]
        for f in fetch(INDEX)
        if isinstance(f, dict)
        and "Bluetooth" in f.get("name", "")
        and f["name"].endswith(".json")
    )
    if not files:
        sys.exit("no Bluetooth interfaces found — has the layout changed?")

    lines = [
        "# MDN's status for each Web Bluetooth member.",
        "# Source: mdn/browser-compat-data",
        "# Generated by scripts/update.sh surface — do not edit.",
        "#",
        "# `Interface.member status[,status]`. This is the *shipped* view and is",
        "# narrower than the specification's IDL: a member the standard defines",
        "# but nobody implements does not appear here at all. Its purpose is the",
        "# status, which the IDL does not carry.",
        "",
    ]
    total = 0
    for name in files:
        data = fetch(f"{BASE}/{name}")["api"]
        for interface, body in sorted(data.items()):
            for member, entry in sorted(body.items()):
                if member.startswith("__") or not isinstance(entry, dict):
                    continue
                status = entry.get("__compat", {}).get("status", {})
                flags = sorted(k for k, v in status.items() if v) or ["unknown"]
                lines.append(f"{interface}.{member} {','.join(flags)}")
                total += 1

    pathlib.Path("crates/webbluetooth-core/spec/web-bluetooth-status.txt").write_text("\n".join(lines) + "\n")
    print("wrote crates/webbluetooth-core/spec/web-bluetooth-status.txt")
    print(f"  members: {total}")


if __name__ == "__main__":
    main()
