#!/usr/bin/env python3
"""Turn the Web Bluetooth IDL into crates/webbluetooth-core/spec/web-bluetooth-surface.txt.

The source is the IDL the standard itself declares, extracted by w3c/webref
straight from the specification. MDN's browser-compat-data was the earlier
source and is narrower: it records what browsers have *shipped*, so members
the standard defines but nobody has implemented are simply absent from it.
Parity with the standard means the standard is the oracle.

One `Interface.member` per line, with the kind recorded so the conformance test
can tell an interface from a dictionary — a dictionary is a call's arguments,
which Rust spells as a builder rather than as members.
"""

import pathlib
import re
import sys
import urllib.request

# Two files, because the standard is two documents: Web Bluetooth and the
# Scanning extension that adds `requestLEScan` and `watchAdvertisements`. They
# were one `web-bluetooth.idl` until webref split them, and the halves ended up
# under names that read backwards — `bluetooth.idl` is the scanning half and
# `bluetooth-scanning.idl` is the core one. Both are fetched and concatenated;
# `Bluetooth` is declared in one and extended by a `partial` in the other, so
# its members merge under the single name either way.
BASE = "https://raw.githubusercontent.com/w3c/webref/main/ed/idl"
URLS = (f"{BASE}/bluetooth-scanning.idl", f"{BASE}/bluetooth.idl")

# `[Extended] attributes`, comments and trailing punctuation are noise here;
# what matters is the declared name of each member.
DECL = re.compile(
    r"(?:\[[^\]]*\]\s*)?(interface mixin|interface|dictionary|enum)\s+(\w+)[^{]*\{(.*?)\n\};",
    re.S,
)
MEMBER = re.compile(r"(\w+)\s*(?:\(|;|$)")


def members_of(body: str) -> list[str]:
    """Each member declared in an interface or dictionary body.

    Split on `;` rather than on newlines: a declaration wraps when its argument
    list is long, and reading those lines separately picks up argument names as
    though they were members — which is how `watchAdvertisements(optional
    WatchAdvertisementsOptions options)` first yielded a member called
    `options`.
    """
    found = []
    for statement in body.split(";"):
        # Strip comments and collapse the wrapping.
        statement = re.sub(r"//[^\n]*", " ", statement)
        statement = " ".join(statement.split())
        if not statement:
            continue
        # An operation: the name is the identifier before its argument list.
        # An attribute or dictionary field: the name is the last identifier,
        # before any default value.
        match = re.search(r"(\w+)\s*\(", statement) or re.search(
            r"(\w+)\s*(?:=[^=]*)?$", statement
        )
        if match and match.group(1) not in ("required", "readonly", "attribute"):
            found.append(match.group(1))
    return found


def main() -> None:
    idl = "\n".join(
        urllib.request.urlopen(url, timeout=60).read().decode() for url in URLS
    )
    # One check per half. A rename upstream is a 404 and stops this outright,
    # but a *reshuffle* is silent: whichever half moved would simply contribute
    # nothing, and the surface would shrink without anything saying so.
    for marker in ("BluetoothRemoteGATTServer", "BluetoothLEScan"):
        if marker not in idl:
            sys.exit(f"fetched IDL is missing {marker} — has webref moved it?")

    lines = [
        "# The Web Bluetooth surface, from the specification's own IDL.",
        "# Source: w3c/webref ed/idl/bluetooth-scanning.idl + bluetooth.idl",
        "# Generated by scripts/update.sh surface — do not edit.",
        "#",
        "# `kind Interface.member` per line. The kind matters: a dictionary is",
        "# a call's arguments, which Rust spells as a builder rather than as",
        "# members of a type.",
        "",
    ]
    total = 0
    for kind, name, body in DECL.findall(idl):
        for member in members_of(body):
            lines.append(f"{kind.replace(' ', '-')} {name}.{member}")
            total += 1

    pathlib.Path("crates/webbluetooth-core/spec/web-bluetooth-surface.txt").write_text("\n".join(lines) + "\n")
    print("wrote crates/webbluetooth-core/spec/web-bluetooth-surface.txt")
    print(f"  members: {total}")


if __name__ == "__main__":
    main()
